@startuml
left to right direction

skinparam actorStyle awesome
skinparam packageStyle rectangle

actor Osoba
actor Korisnik
actor Volonter
actor "Administrator udruženja" as Admin
actor "Sistemski administrator" as SysAdmin


Korisnik <|-- Volonter
Korisnik <|-- Admin

rectangle "Aplikacija za udomljavanje životinja" {

'=========================
' Osoba i Korisnik
'=========================

usecase "Prijava" as UC1
usecase "Odjava" as UC2
usecase "Pregled svih\nudruženja" as UC3
usecase "Pregled dostupnih\nživotinja" as UC4

usecase "Zahtev za\nvolontiranje" as UC5
usecase "Zahtev za\nudomljavanje" as UC6

usecase "Pregled životinja\nu udruženju" as UC29
usecase "<<CRUD>>\nIzmena\nkorisničkih\npodataka" as UC30

'=========================
' Sistemski administrator
'=========================

usecase "<<CRUD>>\nRegistracija udruženja" as UC8
usecase "<<CRUD>>\nRegistracija\nadministratora\nudruženja" as UC9
usecase "Pregled svih\nkorisnika" as UC10

'=========================
' Administrator udruženja
'=========================

usecase "<<CRUD>>\nRegistracija\nvolontera" as UC11

usecase "Prihvatanje\nzahteva za\nvolontiranje" as UC12
usecase "Odbijanje\nzahteva za\nvolontiranje" as UC13

usecase "Pregled svih\nvolontera udruženja" as UC15

usecase "Izveštaj o\nudomljavanjima" as UC17
usecase "Objava izveštaja\no udomljavanjima" as UC18

usecase "Import i pregled\nizvoda računa\nudruženja" as UC21

usecase "Prihvatanje zahteva\nza udomljavanje" as UC22

usecase "Prikaz svih\nudomitelja" as UC24

usecase "<<CRUD>>\nRegistracija\nudomitelja" as UC25

usecase "<<CRUD>>\nDodavanje\nživotinja" as UC26

usecase "Odbijanje zahteva\nza udomljavanje" as UC31

'=========================
' Volonter
'=========================

usecase "Uzimanje\nživotinje u\nsmeštaj" as UC28

}

'=========================
' Akteri
'=========================

Osoba --> UC3
Osoba --> UC5
Osoba --> UC6

Korisnik --> UC1
Korisnik --> UC2
Korisnik --> UC29
Korisnik --> UC30

SysAdmin --> UC8
SysAdmin --> UC10
SysAdmin --> UC1
SysAdmin --> UC2

Admin --> UC12
Admin --> UC13
Admin --> UC15
Admin --> UC17
Admin --> UC21
Admin --> UC22
Admin --> UC24
Admin --> UC26
Admin --> UC31

Volonter --> UC22
Volonter --> UC24
Volonter --> UC28
Volonter --> UC31

'=========================
' include
'=========================

UC8 ..> UC9 : <<include>>

UC12 ..> UC11 : <<include>>

'=========================
' extend
'=========================

UC4 ..> UC3 : <<extend>>

UC18 ..> UC17 : <<extend>>

UC25 ..> UC22 : <<extend>>
@enduml
