@startuml
left to right direction

skinparam actorStyle awesome

actor Korisnik
actor Volonter
actor "Administrator udruženja" as Admin
actor "Sistemski administrator" as SysAdmin

Korisnik <|-- Volonter
Korisnik <|-- Admin
Korisnik <|-- SysAdmin

rectangle "Aplikacija za udomljavanje životinja" {

usecase "Prijava" as UC1
usecase "Odjava" as UC2
usecase "Pregled svih\nudruženja" as UC3
usecase "Pregled dostupnih\nživotinja" as UC4

usecase "Zahtev za\nvolontiranje" as UC5
usecase "Zahtev za\nudomljavanje" as UC6

usecase "CRUD\nregistracija udruženja" as UC7
usecase "Pregled svih\nkorisnika" as UC8

usecase "CRUD\nregistracija volontera" as UC9
usecase "Promocija\nvolontera" as UC10
usecase "Pregled svih\nvolontera udruženja" as UC11

usecase "Upravljanje\ndonacijama" as UC12

usecase "Izveštaj o\ndonacijama" as UC13
usecase "Objava izveštaja\no donacijama" as UC22

usecase "Izveštaj o\nudomljavanjima" as UC14
usecase "Objava izveštaja\no udomljavanjima" as UC23

usecase "Import i pregled\nizvoda računa\nudruženja" as UC15

usecase "CRUD\nregistracija\nudomitelja" as UC16

usecase "Prikaz svih\nudomitelja" as UC17

usecase "CRUD\nDodavanje\nživotinja" as UC18

usecase "CRUD\nUnošenje podataka\no udomljavanju" as UC19

usecase "Prihvatanje ili\nodbijanje zahteva\nza udomljavanje" as UC20

usecase "Slanje obaveštenja\nudomitelju" as UC21

}

'=========================
' Veze aktera
'=========================

Korisnik --> UC1
Korisnik --> UC2
Korisnik --> UC3
Korisnik --> UC4
Korisnik --> UC5
Korisnik --> UC6

Volonter --> UC16
Volonter --> UC17
Volonter --> UC18
Volonter --> UC19
Volonter --> UC20

Admin --> UC9
Admin --> UC10
Admin --> UC11
Admin --> UC12
Admin --> UC13
Admin --> UC14
Admin --> UC15
Admin --> UC16
Admin --> UC17
Admin --> UC20

SysAdmin --> UC7
SysAdmin --> UC8

'=========================
' Include
'=========================

UC20 ..> UC21 : <<include>>

'=========================
' Hidden raspored
'=========================

UC13 -[hidden]-> UC22
UC14 -[hidden]-> UC23

'=========================
' Extend
'=========================

UC22 ..> UC13 : <<extend>>
UC23 ..> UC14 : <<extend>>
@enduml
